import time
import RPi.GPIO as GPIO

GPIO.setwarnings(False)
GPIO.setmode(GPIO.BCM)

LED1 = 6
LED2 = 5
LED3 = 25
LED4 = 24
LED5 = 23
LED6 = 22
LED7 = 27
LED8 = 17

GPIO.setup(LED1, GPIO.OUT)
GPIO.setup(LED2, GPIO.OUT)
GPIO.setup(LED3, GPIO.OUT)
GPIO.setup(LED4, GPIO.OUT)
GPIO.setup(LED5, GPIO.OUT)
GPIO.setup(LED6, GPIO.OUT)
GPIO.setup(LED7, GPIO.OUT)
GPIO.setup(LED8, GPIO.OUT)

try:
    while True:
		# Pattern 1
        GPIO.output(LED1, GPIO.HIGH)
        time.sleep(0.3)
        GPIO.output(LED1, GPIO.LOW)
        time.sleep(0.3)
        GPIO.output(LED2, GPIO.HIGH)
        time.sleep(0.3)
        GPIO.output(LED2, GPIO.LOW)
        time.sleep(0.3)
        GPIO.output(LED3, GPIO.HIGH)
        time.sleep(0.3)
        GPIO.output(LED3, GPIO.LOW)
        time.sleep(0.3)
        GPIO.output(LED4, GPIO.HIGH)
        time.sleep(0.3)
        GPIO.output(LED4, GPIO.LOW)
        time.sleep(0.3)
        GPIO.output(LED5, GPIO.HIGH)
        time.sleep(0.3)
        GPIO.output(LED5, GPIO.LOW)
        time.sleep(0.3)
        GPIO.output(LED6, GPIO.HIGH)
        time.sleep(0.3)
        GPIO.output(LED6, GPIO.LOW)
        time.sleep(0.3)
        GPIO.output(LED7, GPIO.HIGH)
        time.sleep(0.3)
        GPIO.output(LED7, GPIO.LOW)
        time.sleep(0.3)
        GPIO.output(LED8, GPIO.HIGH)
        time.sleep(0.3)
        GPIO.output(LED8, GPIO.LOW)
        time.sleep(0.3)
        GPIO.output(LED7, GPIO.HIGH)
        time.sleep(0.3)
        GPIO.output(LED7, GPIO.LOW)
        time.sleep(0.3)
        GPIO.output(LED6, GPIO.HIGH)
        time.sleep(0.3)
        GPIO.output(LED6, GPIO.LOW)
        time.sleep(0.3)
        GPIO.output(LED5, GPIO.HIGH)
        time.sleep(0.3)
        GPIO.output(LED5, GPIO.LOW)
        time.sleep(0.3)
        GPIO.output(LED4, GPIO.HIGH)
        time.sleep(0.3)
        GPIO.output(LED4, GPIO.LOW)
        time.sleep(0.3)
        GPIO.output(LED3, GPIO.HIGH)
        time.sleep(0.3)
        GPIO.output(LED3, GPIO.LOW)
        time.sleep(0.3)
        GPIO.output(LED2, GPIO.HIGH)
        time.sleep(0.3)
        GPIO.output(LED2, GPIO.LOW)
        time.sleep(0.3)
        GPIO.output(LED1, GPIO.HIGH)
        time.sleep(0.3)
        GPIO.output(LED1, GPIO.LOW)

        time.sleep(0.3)
        
        # Pattern 2
        GPIO.output(LED1, GPIO.HIGH)
        GPIO.output(LED3, GPIO.HIGH)
        GPIO.output(LED5, GPIO.HIGH)
        GPIO.output(LED7, GPIO.HIGH)
        time.sleep(0.3)
        GPIO.output(LED1, GPIO.LOW)
        GPIO.output(LED3, GPIO.LOW)
        GPIO.output(LED5, GPIO.LOW)
        GPIO.output(LED7, GPIO.LOW)
        time.sleep(0.3)
        GPIO.output(LED2, GPIO.HIGH)
        GPIO.output(LED4, GPIO.HIGH)
        GPIO.output(LED6, GPIO.HIGH)
        GPIO.output(LED8, GPIO.HIGH)
        time.sleep(0.3)
        GPIO.output(LED2, GPIO.LOW)
        GPIO.output(LED4, GPIO.LOW)
        GPIO.output(LED6, GPIO.LOW)
        GPIO.output(LED8, GPIO.LOW)
        time.sleep(0.3)
        GPIO.output(LED1, GPIO.HIGH)
        GPIO.output(LED3, GPIO.HIGH)
        GPIO.output(LED5, GPIO.HIGH)
        GPIO.output(LED7, GPIO.HIGH)
        time.sleep(0.3)
        GPIO.output(LED1, GPIO.LOW)
        GPIO.output(LED3, GPIO.LOW)
        GPIO.output(LED5, GPIO.LOW)
        GPIO.output(LED7, GPIO.LOW)

        time.sleep(0.3)

		# Pattern 3
        GPIO.output(LED1, GPIO.HIGH)
        GPIO.output(LED8, GPIO.HIGH)
        time.sleep(0.3)
        GPIO.output(LED1, GPIO.LOW)
        GPIO.output(LED8, GPIO.LOW)
        time.sleep(0.3)
        GPIO.output(LED2, GPIO.HIGH)
        GPIO.output(LED7, GPIO.HIGH)
        time.sleep(0.3)
        GPIO.output(LED2, GPIO.LOW)
        GPIO.output(LED7, GPIO.LOW)
        time.sleep(0.3)
        GPIO.output(LED3, GPIO.HIGH)
        GPIO.output(LED6, GPIO.HIGH)
        time.sleep(0.3)
        GPIO.output(LED3, GPIO.LOW)
        GPIO.output(LED6, GPIO.LOW)
        time.sleep(0.3)
        GPIO.output(LED1, GPIO.HIGH)
        GPIO.output(LED8, GPIO.HIGH)
        time.sleep(0.3)
        GPIO.output(LED1, GPIO.LOW)
        GPIO.output(LED8, GPIO.LOW)
        time.sleep(0.3)
        GPIO.output(LED4, GPIO.HIGH)
        GPIO.output(LED5, GPIO.HIGH)
        time.sleep(0.3)
        GPIO.output(LED4, GPIO.LOW)
        GPIO.output(LED5, GPIO.LOW)

        time.sleep(0.3)

except KeyboardInterrupt:
    GPIO.cleanup()